extends Node
## Autoload: indexes every Sidekick FBX part by slot and caches loaded scenes.
##
## Data source: res://assets/sidekick/goblin_fighters/_part_index.json
## (generated by the extraction script from the unitypackage).
##
## Usage:
##   var parts = SidekickPartLibrary.parts_for_slot("torso")  # [PartEntry]
##   var scene = SidekickPartLibrary.load_part_scene("torso", "SK_GOBL_BASE_01_10TORS_GO01")
##
## Bulletproofing: all lookups return null / empty on miss, never crash. Missing
## FBX files are logged once, not spammed.

const INDEX_PATH := "res://assets/sidekick/goblin_fighters/_part_index.json"

## Canonical slot order — used by the customizer UI to display slots top-to-bottom.
## Slots not in this list still work at runtime; they just won't get a dedicated row.
const SLOT_ORDER := [
	"head", "hair", "facial_hair", "eyebrow_l", "eyebrow_r",
	"eye_l", "eye_r", "ear_l", "ear_r", "nose", "teeth", "tongue",
	"torso", "arm_upper_l", "arm_upper_r", "arm_lower_l", "arm_lower_r",
	"hand_l", "hand_r", "hips", "leg_l", "leg_r", "foot_l", "foot_r",
	"acc_head", "acc_face", "acc_back",
	"acc_shoulder_l", "acc_shoulder_r",
	"acc_elbow_l", "acc_elbow_r",
	"acc_hip_front", "acc_hip_back", "acc_hip_l", "acc_hip_r",
	"acc_knee_l", "acc_knee_r",
	"wrap",
]

## Slots that should be body-paired (setting torso auto-sets arms/hands if matching variant exists)
const BODY_PAIRED_SLOTS := [
	"torso", "arm_upper_l", "arm_upper_r", "arm_lower_l", "arm_lower_r",
	"hand_l", "hand_r", "hips", "leg_l", "leg_r", "foot_l", "foot_r",
]

## Skinned-mesh slots (use the shared Skeleton3D). Everything else is also skinned
## in this pack but listed here for clarity / future accessory bone-parenting.
const SKINNED_SLOTS := SLOT_ORDER  # all Sidekick parts are skinned to the master rig

class PartEntry:
	var name: String
	var slot: String
	var species: String
	var pack: String
	var variant: String
	var is_base: bool
	var res_path: String

	func _to_string() -> String:
		return "PartEntry(%s @ %s v%s)" % [name, slot, variant]

var _index: Dictionary = {}  # slot -> Array[PartEntry]
var _scene_cache: Dictionary = {}  # res_path -> PackedScene
var _missing_warned: Dictionary = {}  # res_path -> true (dedupe warnings)
var _loaded: bool = false


func _ready() -> void:
	load_index()


func load_index() -> void:
	_index.clear()
	_scene_cache.clear()
	_missing_warned.clear()
	_loaded = false
	if not FileAccess.file_exists(INDEX_PATH):
		push_error("[SidekickPartLibrary] index not found at %s — run the extraction script" % INDEX_PATH)
		return
	var f := FileAccess.open(INDEX_PATH, FileAccess.READ)
	var txt := f.get_as_text()
	f.close()
	var parsed = JSON.parse_string(txt)
	if typeof(parsed) != TYPE_DICTIONARY:
		push_error("[SidekickPartLibrary] index JSON malformed")
		return
	for slot in parsed:
		var arr: Array[PartEntry] = []
		for raw in parsed[slot]:
			var e := PartEntry.new()
			e.name = raw.get("name", "")
			e.slot = slot
			e.species = raw.get("species", "")
			e.pack = raw.get("pack", "")
			e.variant = raw.get("variant", "")
			e.is_base = raw.get("is_base", false)
			e.res_path = raw.get("res_path", "")
			arr.append(e)
		_index[slot] = arr
	_loaded = true
	print("[SidekickPartLibrary] loaded %d slots, %d total parts" % [_index.size(), total_part_count()])


func is_loaded() -> bool: return _loaded


func total_part_count() -> int:
	var n := 0
	for slot in _index: n += (_index[slot] as Array).size()
	return n


## All slot names, in canonical order, with unknown slots appended.
func all_slots() -> Array[String]:
	var out: Array[String] = []
	for s in SLOT_ORDER:
		if _index.has(s): out.append(s)
	for s in _index.keys():
		if not SLOT_ORDER.has(s): out.append(s)
	return out


## Returns Array[PartEntry] for a slot, or [] on miss.
func parts_for_slot(slot: String) -> Array[PartEntry]:
	return _index.get(slot, [] as Array[PartEntry])


## Case-sensitive lookup by part name within a slot. null on miss.
func find_part(slot: String, part_name: String) -> PartEntry:
	for p in parts_for_slot(slot):
		if p.name == part_name: return p
	return null


func has_part(slot: String, part_name: String) -> bool:
	return find_part(slot, part_name) != null


## Returns the imported PackedScene for a part, loading on first request.
## null = FBX missing or failed to import; caller must null-check.
func load_part_scene(slot: String, part_name: String) -> PackedScene:
	var entry := find_part(slot, part_name)
	if entry == null: return null
	if _scene_cache.has(entry.res_path):
		return _scene_cache[entry.res_path]
	if not ResourceLoader.exists(entry.res_path):
		if not _missing_warned.has(entry.res_path):
			push_warning("[SidekickPartLibrary] FBX not imported yet: %s" % entry.res_path)
			_missing_warned[entry.res_path] = true
		return null
	var scene := ResourceLoader.load(entry.res_path) as PackedScene
	if scene == null:
		if not _missing_warned.has(entry.res_path):
			push_error("[SidekickPartLibrary] failed to load %s" % entry.res_path)
			_missing_warned[entry.res_path] = true
		return null
	_scene_cache[entry.res_path] = scene
	return scene


## Picks a reasonable default for each slot so a freshly-instantiated
## SidekickCharacter has something to render. Used by the customizer "Reset"
## button and as the fallback when apply_preset is called with empty parts.
func default_preset() -> CharacterPreset:
	var p := CharacterPreset.new()
	p.display_name = "Default Goblin"
	p.archetype = "goblin_base"
	# Pick the first base part for each body slot; leave accessories empty.
	for slot in SLOT_ORDER:
		var parts := parts_for_slot(slot)
		if parts.is_empty(): continue
		var is_accessory: bool = (slot as String).begins_with("acc_")
		if is_accessory:
			p.parts[slot] = ""  # hidden by default
			continue
		# prefer a base (Species) part with variant "01"
		var chosen: PartEntry = null
		for e in parts:
			if e.is_base and e.variant == "01":
				chosen = e
				break
		if chosen == null:
			chosen = parts[0]
		p.parts[slot] = chosen.name
	return p
