extends Node
## Autoload: procgen-friendly query API over the per-pack `_tag_manifest.json`
## files generated by `_tools/synty_classify.gd`.
##
## Instead of hardcoding prefab paths or guessing from names, systems ask:
##   AssetTags.query({"role": "env_wall_tile", "aesthetic": "cave", "tileable": true})
##   → Array[Dictionary] of matching prefab tag records, sorted by tri count.
##
## Each tag record has: path, pack, size_m [x,y,z], origin [x,y,z], tri_count,
## shape, origin_kind, facing_axis, scale_group, aesthetic, role, tileable.

const MANIFEST_GLOB := "res://assets/synty/*/_tag_manifest.json"

var _all_tags: Array = []
var _loaded: bool = false


func _ready() -> void:
	_load_manifests()


func _load_manifests() -> void:
	_all_tags.clear()
	var synty_dir: DirAccess = DirAccess.open("res://assets/synty")
	if synty_dir == null:
		push_warning("[AssetTags] no res://assets/synty directory")
		return
	for pack in synty_dir.get_directories():
		var mf: String = "res://assets/synty/%s/_tag_manifest.json" % pack
		if not FileAccess.file_exists(mf):
			continue
		var f: FileAccess = FileAccess.open(mf, FileAccess.READ)
		var parsed: Variant = JSON.parse_string(f.get_as_text())
		f.close()
		if typeof(parsed) != TYPE_DICTIONARY or not parsed.has("tags"):
			continue
		for t in parsed["tags"]:
			_all_tags.append(t)
	_loaded = true
	print("[AssetTags] loaded %d tag records" % _all_tags.size())


## Query tags. `filters` is a Dictionary of field → expected value. String
## values compare equal; booleans likewise; arrays mean "value ∈ array".
## Returns matches sorted by ascending tri_count (cheapest first).
func query(filters: Dictionary) -> Array:
	var out: Array = []
	for t in _all_tags:
		if _matches(t, filters):
			out.append(t)
	out.sort_custom(func(a, b): return a.tri_count < b.tri_count)
	return out


## Convenience: return the single best match for `filters`, or null.
## "Best" = lowest tri_count satisfying the filter.
func query_one(filters: Dictionary) -> Dictionary:
	var results: Array = query(filters)
	return results[0] if not results.is_empty() else {}


## Load the PackedScene referenced by a tag record. Returns null on miss.
func load_prefab(tag: Dictionary) -> PackedScene:
	if not tag.has("path"):
		return null
	return load(tag.path)


func _matches(tag: Dictionary, filters: Dictionary) -> bool:
	for key in filters:
		var expected: Variant = filters[key]
		if not tag.has(key):
			return false
		var actual: Variant = tag[key]
		if typeof(expected) == TYPE_ARRAY:
			if not (actual in expected):
				return false
		elif actual != expected:
			return false
	return true
