extends SceneTree
## Generated by synty_to_godot.py — do not hand-edit; re-run the converter.
const SYNTY_ROOT: String = "res://assets/synty"
const CLASSIFIER_PATH: String = "res://assets/synty/_synty_animation_classifier.gd"

func _init() -> void:
	var Classifier: GDScript = load(CLASSIFIER_PATH)
	if Classifier == null:
		push_error("[ClassifyPack] classifier not loadable"); quit(1); return
	var packs: PackedStringArray = _list_packs()
	if packs.is_empty(): quit(0); return
	for pack: String in packs:
		_classify_pack("%s/%s" % [SYNTY_ROOT, pack], Classifier)
	var anim_pack: String = _find_animation_pack(packs)
	if anim_pack != "":
		print("\n[ClassifyPack] animation bank = %s — aliasing character packs" % anim_pack)
		for pack: String in packs:
			if pack == anim_pack: continue
			# Ensure character packs without their own anims still get a
			# library so bank-aliasing can populate it. Otherwise per-prefab
			# AnimationPlayer references a nonexistent _library.tres.
			_ensure_library_exists("%s/%s" % [SYNTY_ROOT, pack])
			_alias_to_bank("%s/%s" % [SYNTY_ROOT, pack], "%s/%s" % [SYNTY_ROOT, anim_pack])
	quit(0)

func _ensure_library_exists(pack_dir: String) -> void:
	# Pack has rigged characters (Prefabs/Character_* or Prefabs/SM_Chr_*)
	# but no Animations dir or no _library.tres? Create an empty library so
	# the alias pass can populate it.
	var lib_path: String = "%s/Animations/_library.tres" % pack_dir
	if ResourceLoader.exists(lib_path): return
	var prefabs_dir: DirAccess = DirAccess.open("%s/Prefabs" % pack_dir)
	if prefabs_dir == null: return
	var has_chars: bool = false
	for f: String in prefabs_dir.get_files():
		if f.begins_with("Character_") or (f.begins_with("SM_Chr_") and not f.begins_with("SM_Chr_Attach_")):
			has_chars = true; break
	if not has_chars: return
	DirAccess.make_dir_recursive_absolute("%s/Animations" % pack_dir)
	var lib: AnimationLibrary = AnimationLibrary.new()
	ResourceSaver.save(lib, lib_path)
	print("[ClassifyPack] %s: created empty library (no bundled anims)" % pack_dir.get_file())

func _list_packs() -> PackedStringArray:
	var out: PackedStringArray = PackedStringArray()
	var da: DirAccess = DirAccess.open(SYNTY_ROOT)
	if da == null: return out
	for d: String in da.get_directories():
		if d.begins_with("_"): continue
		out.append(d)
	return out

func _find_animation_pack(packs: PackedStringArray) -> String:
	var best: String = ""
	var best_count: int = 0
	for pack: String in packs:
		var dir_path: String = "%s/%s/Animations" % [SYNTY_ROOT, pack]
		var da: DirAccess = DirAccess.open(dir_path)
		if da == null: continue
		var n: int = 0
		for f: String in da.get_files():
			if f.begins_with("A_") and f.ends_with(".tres"): n += 1
		if n > best_count:
			best_count = n; best = pack
	return best if best_count >= 5 else ""

func _alias_to_bank(char_pack_dir: String, anim_pack_dir: String) -> void:
	var bank_path: String = "%s/Animations/_library.tres" % anim_pack_dir
	var char_lib_path: String = "%s/Animations/_library.tres" % char_pack_dir
	if not ResourceLoader.exists(bank_path) or not ResourceLoader.exists(char_lib_path): return
	var bank: AnimationLibrary = load(bank_path) as AnimationLibrary
	var char_lib: AnimationLibrary = load(char_lib_path) as AnimationLibrary
	if bank == null or char_lib == null: return
	var aliased: Array[String] = []
	for role: StringName in bank.get_animation_list():
		var bank_anim: Animation = bank.get_animation(role)
		if bank_anim == null: continue
		if char_lib.has_animation(role): char_lib.remove_animation(role)
		char_lib.add_animation(role, bank_anim)
		aliased.append(String(role))
	ResourceSaver.save(char_lib, char_lib_path)
	print("  %s ← bank roles: %s" % [char_pack_dir.get_file(), str(aliased)])

func _is_cyclical(role: String) -> bool:
	return role in ["walk", "run", "idle", "wave"]

func _clip_priority(filename: String, role: String) -> int:
	var name: String = filename.to_lower()
	var score: int = 0
	if name.contains("_masc"): score += 100
	elif name.contains("_femn"): score += 0
	else: score += 50
	if name.begins_with("a_%s_f_" % role.to_lower()): score += 200
	elif name.begins_with("a_%s_" % role.to_lower()): score += 50
	for bad: String in ["crouch", "strafe", "towalk", "torun", "tostand", "additive", "inair"]:
		if name.contains(bad): score -= 80
	if name.contains("rootmotion"): score -= 60
	return score

func _strip_root_motion_tracks(anim: Animation) -> bool:
	# Physics-driven characters own world transform — root position/rotation
	# tracks fight that. Strip POS on all bones + ROT on Hips/Root/Pelvis.
	var removed: bool = false
	var root_bones: PackedStringArray = PackedStringArray(["Hips", "Root", "Pelvis"])
	for t: int in range(anim.get_track_count() - 1, -1, -1):
		var ttype: int = anim.track_get_type(t)
		if ttype == Animation.TYPE_POSITION_3D:
			anim.remove_track(t); removed = true; continue
		if ttype == Animation.TYPE_ROTATION_3D:
			var path_str: String = String(anim.track_get_path(t))
			var bone_name: String = path_str.get_slice(":", path_str.get_slice_count(":") - 1)
			if bone_name in root_bones:
				anim.remove_track(t); removed = true
	return removed

func _classify_pack(pack_dir: String, Classifier: GDScript) -> void:
	var anims_dir: String = "%s/Animations" % pack_dir
	var da: DirAccess = DirAccess.open(anims_dir)
	if da == null: return
	var role_to_path: Dictionary = {}
	for f: String in da.get_files():
		if not f.ends_with(".tres"): continue
		var anim_path: String = "%s/%s" % [anims_dir, f]
		var anim: Animation = load(anim_path) as Animation
		if anim == null: continue
		var role: String = Classifier.classify_with_hint(anim, f)
		if _strip_root_motion_tracks(anim):
			ResourceSaver.save(anim, anim_path)
		if _is_cyclical(role) and anim.loop_mode == Animation.LOOP_NONE:
			anim.loop_mode = Animation.LOOP_LINEAR
			ResourceSaver.save(anim, anim_path)
		var score: int = _clip_priority(f, role)
		var prev_score: int = role_to_path.get(role + "::score", -1)
		if not role_to_path.has(role) or score > prev_score:
			role_to_path[role] = anim_path
			role_to_path[role + "::score"] = score
	if role_to_path.is_empty(): return
	var lib: AnimationLibrary = AnimationLibrary.new()
	for role: String in role_to_path:
		if role.contains("::"): continue
		var anim: Animation = load(role_to_path[role]) as Animation
		if anim == null: continue
		lib.add_animation(role, anim)
	var lib_path: String = "%s/Animations/_library.tres" % pack_dir
	ResourceSaver.save(lib, lib_path)
	print("[ClassifyPack] %s → %s" % [pack_dir.get_file(), str(role_to_path.keys())])
