class_name SyntyAnimationClassifier
extends RefCounted
## Generated by synty_to_godot.py — do not hand-edit; re-run the converter.
##
## Heuristic classifier that infers an animation's gameplay ROLE from track
## motion + filename hints. Roles: walk/run/idle/wave/attack/death/unknown.

const ROLE_DEATH:   String = "death"
const ROLE_RUN:     String = "run"
const ROLE_WALK:    String = "walk"
const ROLE_IDLE:    String = "idle"
const ROLE_WAVE:    String = "wave"
const ROLE_ATTACK:  String = "attack"
const ROLE_UNKNOWN: String = "unknown"

const BONE_BUCKETS: Dictionary = {
	"root":  ["root", ":hips"],
	"leg":   ["leg", "ankle", "foot", "knee", "shin", "thigh"],
	"arm":   ["shoulder", "elbow", "hand", "arm", "wrist", "clavicle"],
	"head":  ["head", "neck", "jaw"],
	"spine": ["spine", "chest", "torso", "back"],
}

const FILENAME_ROLE_HINTS: Array = [
	["sprint", ROLE_RUN], ["run", ROLE_RUN], ["walk", ROLE_WALK],
	["crouch", ROLE_WALK], ["idle", ROLE_IDLE], ["headlook", ROLE_IDLE],
	["bodylook", ROLE_IDLE], ["land", ROLE_IDLE], ["jump", ROLE_ATTACK],
	["inair", ROLE_ATTACK], ["death", ROLE_DEATH], ["wave", ROLE_WAVE],
	["gesture", ROLE_WAVE], ["attack", ROLE_ATTACK],
]

static func classify_with_hint(anim: Animation, source_filename_hint: String) -> String:
	if anim == null or anim.length <= 0.0: return ROLE_UNKNOWN
	var hint_role: String = role_from_filename(source_filename_hint)
	if hint_role != "": return hint_role
	return verdict(analyze(anim))

static func role_from_filename(filename: String) -> String:
	if filename == "": return ""
	var lc: String = filename.to_lower()
	for entry: Array in FILENAME_ROLE_HINTS:
		if lc.contains(entry[0]): return entry[1]
	return ""

static func analyze(anim: Animation) -> Dictionary:
	var s: Dictionary = {
		"length": anim.length, "root_horizontal_total": 0.0,
		"root_horizontal_per_s": 0.0, "root_y_peak_dip": 0.0,
		"root_y_sustained_drop": 0.0, "leg_tracks_moving": 0,
		"arm_tracks_moving": 0, "head_tracks_moving": 0,
		"spine_tracks_moving": 0, "is_cyclical": false,
	}
	for t: int in anim.get_track_count():
		var path: NodePath = anim.track_get_path(t)
		var bucket: String = _bucket_for(str(path))
		var n_keys: int = anim.track_get_key_count(t)
		if n_keys < 2: continue
		var ttype: int = anim.track_get_type(t)
		var first: Variant = anim.track_get_key_value(t, 0)
		var last: Variant = anim.track_get_key_value(t, n_keys - 1)
		var moves: bool = first != last
		if not moves and n_keys >= 3:
			moves = first != anim.track_get_key_value(t, n_keys / 2)
		if not moves: continue
		if bucket == "root" and ttype == Animation.TYPE_POSITION_3D:
			var v0: Vector3 = first as Vector3
			var v_last: Vector3 = last as Vector3
			var max_horiz: float = 0.0
			var max_dip: float = 0.0
			for k: int in n_keys:
				var v: Vector3 = anim.track_get_key_value(t, k) as Vector3
				var horiz: float = Vector2(v.x - v0.x, v.z - v0.z).length()
				if horiz > max_horiz: max_horiz = horiz
				var dip: float = v0.y - v.y
				if dip > max_dip: max_dip = dip
			s.root_horizontal_total = maxf(s.root_horizontal_total, max_horiz)
			s.root_y_peak_dip = maxf(s.root_y_peak_dip, max_dip)
			s.root_y_sustained_drop = maxf(s.root_y_sustained_drop, v0.y - v_last.y)
		elif bucket == "leg": s.leg_tracks_moving += 1
		elif bucket == "arm": s.arm_tracks_moving += 1
		elif bucket == "head": s.head_tracks_moving += 1
		elif bucket == "spine": s.spine_tracks_moving += 1
	if anim.length > 0.01:
		s.root_horizontal_per_s = s.root_horizontal_total / anim.length
	s.is_cyclical = anim.loop_mode != Animation.LOOP_NONE or s.root_horizontal_per_s < 0.1
	return s

static func verdict(s: Dictionary) -> String:
	if s.root_y_sustained_drop > 0.3 and s.root_horizontal_per_s < 1.0: return ROLE_DEATH
	if s.root_horizontal_per_s > 50.0: return ROLE_RUN
	if s.root_horizontal_per_s > 0.1: return ROLE_WALK
	if s.leg_tracks_moving >= 4 and s.arm_tracks_moving >= 2: return ROLE_WALK
	if s.arm_tracks_moving >= 4 and s.leg_tracks_moving <= 1: return ROLE_WAVE
	if (s.spine_tracks_moving + s.head_tracks_moving) >= 1 \
			and s.leg_tracks_moving <= 1 and s.arm_tracks_moving <= 2: return ROLE_IDLE
	if s.arm_tracks_moving + s.leg_tracks_moving >= 4: return ROLE_ATTACK
	return ROLE_UNKNOWN

static func _bucket_for(path_str: String) -> String:
	var p: String = path_str.to_lower()
	for bucket: String in BONE_BUCKETS:
		var keywords: Array = BONE_BUCKETS[bucket]
		for kw: String in keywords:
			if p.contains(kw): return bucket
	return ""
