extends Node
class_name SyntyRigNormalizer
## Generated by synty_to_godot.py — do not hand-edit; re-run the converter.
##
## Walks all child Skeleton3D nodes and renames their bones to canonical
## SkeletonProfileHumanoid names defined in `bone_map`. Also rewrites every
## SkinnedMeshInstance3D's Skin bind names so vertex weights stay attached
## to the right bones after rename (otherwise the mesh "explodes" because
## named skins lose their bone references). Idempotent.

@export var bone_map: BoneMap


func _ready() -> void:
	if bone_map == null or bone_map.profile == null:
		return
	# Build the source→humanoid lookup once.
	var profile: SkeletonProfile = bone_map.profile
	var rename_map: Dictionary = {}  # StringName(source) → String(humanoid)
	for i: int in profile.bone_size:
		var humanoid_name: String = profile.get_bone_name(i)
		var source_name: StringName = bone_map.get_skeleton_bone_name(humanoid_name)
		if source_name != &"":
			rename_map[source_name] = humanoid_name

	# Update Skin binds FIRST, then rename skeleton bones. Order matters:
	# Skin binds reference bones by NAME (per Synty's import setting
	# `skins/use_named_skins=true`); if we rename the skeleton first the
	# binds become stale and the mesh deforms.
	var parent: Node = get_parent()
	for mi_node: Node in _all_mesh_instances(parent):
		_relabel_skin_binds(mi_node as MeshInstance3D, rename_map)
	for skel_node: Node in _all_skeletons(parent):
		_rename_skeleton_bones(skel_node as Skeleton3D, rename_map)

	# Force any AnimationPlayer that started playing BEFORE we ran (callers
	# like Trucker's enemy.gd kick play_walk in their own _ready before our
	# _ready fires) to re-resolve track→bone mappings against the now-renamed
	# bones. Without this re-trigger, Godot's AnimationPlayer caches the
	# initial (failed) lookup of the humanoid-named tracks and the character
	# stays in T-pose despite the bones being correct.
	for ap_node: Node in parent.find_children("*", "AnimationPlayer", true, false):
		var ap: AnimationPlayer = ap_node
		if ap.is_playing():
			var clip: StringName = ap.current_animation
			var pos: float = ap.current_animation_position
			ap.stop()
			ap.play(clip)
			ap.advance(pos)


func _all_skeletons(node: Node) -> Array:
	var out: Array = []
	if node is Skeleton3D:
		out.append(node)
	for c: Node in node.get_children():
		out.append_array(_all_skeletons(c))
	return out


func _all_mesh_instances(node: Node) -> Array:
	var out: Array = []
	if node is MeshInstance3D:
		out.append(node)
	for c: Node in node.get_children():
		out.append_array(_all_mesh_instances(c))
	return out


func _rename_skeleton_bones(skel: Skeleton3D, rename_map: Dictionary) -> void:
	for source_var: Variant in rename_map:
		var source: StringName = source_var
		var humanoid: String = rename_map[source_var]
		var idx: int = skel.find_bone(source)
		if idx < 0:
			continue
		if skel.get_bone_name(idx) == humanoid:
			continue
		skel.set_bone_name(idx, humanoid)


func _relabel_skin_binds(mi: MeshInstance3D, rename_map: Dictionary) -> void:
	if mi.skin == null:
		return
	var skin: Skin = mi.skin
	for i: int in skin.get_bind_count():
		var current: StringName = skin.get_bind_name(i)
		if current == &"":
			continue
		if rename_map.has(current):
			skin.set_bind_name(i, StringName(rename_map[current]))
