extends Node
class_name SyntyStaticCollision
## Generated by synty_to_godot.py — do not hand-edit; re-run the converter.
##
## Builds trimesh static collision for every MeshInstance3D under the parent
## prefab at _ready. Attached automatically to building/environment/prop
## prefabs by the converter so they actually block movement instead of
## being purely visual. Idempotent.
##
## `collision_layer` defaults to 8 (layer 4 = "static world / ground"), the
## same layer the QA sandbox's Ground node uses. This matches the player
## vehicle's `collision_mask`. Override per prop if you need different layers.

@export_flags_3d_physics var collision_layer: int = 8
@export_flags_3d_physics var collision_mask: int = 0

func _ready() -> void:
	var parent: Node = get_parent()
	if parent == null:
		return
	for mi: Node in parent.find_children("*", "MeshInstance3D", true, false):
		var m: MeshInstance3D = mi
		if m.mesh == null:
			continue
		var existing: bool = false
		for c: Node in m.get_children():
			if c is StaticBody3D:
				existing = true
				break
		if existing:
			continue
		m.create_trimesh_collision()
		# Re-fetch the just-created StaticBody3D and configure its layers.
		for c2: Node in m.get_children():
			if c2 is StaticBody3D:
				(c2 as StaticBody3D).collision_layer = collision_layer
				(c2 as StaticBody3D).collision_mask = collision_mask
				break
