extends Node
class_name SyntyShowOnly
## Generated by synty_to_godot.py — do not hand-edit; re-run the converter.
##
## Hides every MeshInstance3D under the parent except the ones whose names
## appear in `keep`. Used by per-character prefabs of multi-character
## consolidated FBX (Rivals' Characters_BR.fbx, Apocalypse's Characters.fbx).

@export var keep: Array[String] = []


func _ready() -> void:
	var parent: Node = get_parent()
	if parent == null:
		return
	for mi: Node in parent.find_children("*", "MeshInstance3D", true, false):
		(mi as MeshInstance3D).visible = mi.name in keep
