extends Node
class_name SyntyUVScroll
## Generated by synty_to_godot.py — do not hand-edit; re-run the converter.
##
## Animates uv1_offset on every MeshInstance3D under the parent prefab to
## fake Synty's animated lava/magma flow shader. Synty's Unity asset uses a
## custom shader with scrolling UVs; we emulate via per-frame offset bump.
## Each MeshInstance3D gets its own Material instance (duplicated from the
## shared one) so prefabs don't all scroll in lockstep when sharing a mat.

@export var scroll_speed: Vector2 = Vector2(0.05, 0.03)

var _instanced_mats: Array[StandardMaterial3D] = []

func _ready() -> void:
	var parent: Node = get_parent()
	if parent == null:
		return
	for mi: Node in parent.find_children("*", "MeshInstance3D", true, false):
		var m: MeshInstance3D = mi
		if m.mesh == null:
			continue
		for s: int in m.mesh.get_surface_count():
			var src_mat: Material = m.get_surface_override_material(s)
			if src_mat == null:
				src_mat = m.mesh.surface_get_material(s)
			if src_mat == null or not (src_mat is StandardMaterial3D):
				continue
			var dup: StandardMaterial3D = (src_mat as StandardMaterial3D).duplicate()
			m.set_surface_override_material(s, dup)
			_instanced_mats.append(dup)

func _process(delta: float) -> void:
	for m: StandardMaterial3D in _instanced_mats:
		var off: Vector3 = m.uv1_offset
		off.x = fposmod(off.x + scroll_speed.x * delta, 1.0)
		off.y = fposmod(off.y + scroll_speed.y * delta, 1.0)
		m.uv1_offset = off
